### PR TITLE
Update react-redux peer dependency

### PR DESCRIPTION
**Pull request by leMaik**
We have a project with react-redux@7 and as far as I can see, redux-devtools work just fine. This PR fixes the peer dependency warning npm gives when installing the package, reducing CLI noise.

### CODE REVIEW

**Comment by tommarien** [comment]
Can someone please check the build server, it looks failing node-gyp build for sqllite3 (on node V12 ;))

**Comment by AndreaCitrolo** [comment]
Hi,
is it safe to use redux-devtools with react-redux@7+ or is the build failing due to incompatibilities?

**Comment by leMaik** [comment]
@AndreaCitrolo It works just fine :+1:

**Comment by timdorr** [comment]
Thanks!

**Pull request merged**
