### PR TITLE
Update unsafe_componentWillReceiveProps react-json-tree

### PR DESCRIPTION
**Pull request by BrunoFenzl**
This PR attempts to solve #635. 
`unsafe_componentWillReceiveProps` is currently used in two components: `JSONTree` and `JSONNestedNode`.

In `JSONTree` I extracted the properties `theme` and `invertTheme` from `Props` to a separate interface and extended the `State` and `Props` interfaces with it. The reason being, that the new static method `getDerivedStateFromProps` does not have access to the current props, so properties that need to be compared should be mirrored in the local state object.

In `JSONNestedNode` there is no need to check for derived state at all. The property `expanded` can be copied to state and re-rendering is checked anyway in the `shouldComponentUpdate` lifecycle hook.

I'm looking forward to feedback and will be glad to refactor if needed.

### CODE REVIEW

**Comment by Methuselah96** [comment]
@BrunoFenzl Thanks for making a PR!

1. `JSONNestedNode`: `getStateFromProps` is now only ever called in the `constructor` when before it was called on every render. I think you might have to call `getDerivedStateFromProps` in order to match the previous behavior unless I'm missing something. I would like to refactor it to remove `expanded` from `state` altogether, but I don't think that's possible without calling `shouldExpandNode` twice since `shouldComponentUpdate` depends on it.
2. `JSONTree`: The React team recommends not copying props to state just to memoize a value. I would prefer using `memoize-one` as suggested in [this blog post](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#what-about-memoization).

**Comment by BrunoFenzl** [comment]
@Methuselah96 Thanks for your feedback!

1. You're right. I had `getDerivedStateFromProps` initially in place but thought it would be redundant because of the check in 
 `shouldComponentUpdate`. I see it now I was clearly wrong.
2. I am aware of the article but didn't want to add another dependency. If it is ok for you, I'll refactor to use memoize-one.

**Comment by Methuselah96** [comment]
@BrunoFenzl Yeah, I'm fine with adding `memoize-one` as a dependency. Thanks!

**Review by dstiers11 — APPROVED** [review]

**Comment by yesh0907** [comment]
Hi, can this PR be merged? Thanks.

**Comment by Methuselah96** [comment]
The feedback I gave still needs to be addressed. Feel free to create your own PR since it seems like this PR might be abandoned.

**Comment by defunctzombie** [comment]
@Methuselah96 Would you be open to a PR which removes these unsafe calls by converting the JSONTree and JSONNestedNode to function components and using hooks?

**Comment by Methuselah96** [comment]
@defunctzombie Yeah, go for it!

**Comment by Methuselah96** [comment]
Resolved by https://github.com/reduxjs/redux-devtools/pull/1288.

**Pull request closed without merging**
