### PR TITLE
Polyfill `chrome.storage.sync` for Electron

### LINKED ISSUE #696: Unchecked runtime.lastError: "sync" is not available in this instance of Chrome
I am using redux-devtools with electron using https://github.com/MarshallOfSound/electron-devtools-installer
But in console I am getting following, error goes away when I remove redux-devtools 

```
Unchecked runtime.lastError: "sync" is not available in this instance of Chrome
Error handling response: TypeError: Cannot read property 'filter' of undefined
    at chrome-extension://lmhkpmbekcpmknklioeibfkpmmfibljd/js/content.bundle.js:1:21235
```

### PR DESCRIPTION
**Pull request by zhuhaow**
`chrome.storage.sync` is not supported on Electron (https://www.electronjs.org/docs/api/extensions#chromestorage).

Fix #696

### CODE REVIEW

**Review by Methuselah96 — APPROVED** [review]

**Comment by dimitropoulos** [comment]
hi! :)  friendly request to know if there's something left to be done here before this can be merged and released?  can I help?

**Comment by dimitropoulos** [comment]
great! thanks! any idea when this might be released?

much appreciated.

**Comment by Methuselah96** [comment]
@timdorr Can you release this if this looks good to you? I don't think I have access for updating the extension.

**Comment by muhajirdev** [comment]
is this released?

**Comment by timdorr** [comment]
I haven't pushed it out yet.

**Comment by dimitropoulos** [comment]
hey @timdorr, sorry to nag, but this is blocking us from using the redux-devtools over on insomnia, and the redux-devtools is one of my favorite tools I tend to use.  ([context](https://github.com/Kong/insomnia/pull/3390)).

Is there anything I can do to help with the release or can you think of some other way to go about getting this fix?

much appreciated.

**Comment by timdorr** [comment]
I pushed it out last week as a new patch release.

**Comment by dimitropoulos** [comment]
ahh, I was watching for a release on this repo, but that makes sense.  Great, thanks!

by the way, the fix works :)  I had to delete the prior state first, but it works now.  I got some error about migration failing, right after the storage.sync error in this PR, which I'm assuming is related.

**Comment by jamesmontalvo3** [comment]
FYI for anyone else still having the issue, to pick up the new version I had to temporarily do the following:

```diff
- installExtension(REDUX_DEVTOOLS, { loadExtensionOptions: { allowFileAccess: true } }});
+ installExtension(REDUX_DEVTOOLS, { loadExtensionOptions: { allowFileAccess: true }, forceDownload: true }});
```

Doing `npm remove electron && npm install electron` didn't work for me to uninstall extensions, though other threads suggested that worked. I'm guessing my machine cached Electron config and installed extensions and others do not (I'm running Windows).

**Pull request merged**
