### PR TITLE
Fix #1382 - React Native - Hermes Engine isn't supporting `for await` yet

### LINKED ISSUE #1382: React-native Hermes app has an issue with `for await`
React-native bundler for hermes app doesn't support `for await` construction. I had to replace it in this file `@redux-devtools/remote/lib/cjs/devTools.js` at 4 places with this code. 
```
let consumer = this.socket.listener('error').createConsumer();
while (true) {
          const {value: data, done} = await consumer.next();
          if (done) break;
        // for await (const data of this.socket.listener('error')) {
```
Then i got a connection up and running.

Could you fix that please ?

### PR DESCRIPTION
**Pull request by LunatiqueCoder**
Hello!

This PR fixes #1382. Shortly, React Native's JavaScript Engine, Hermes, isn't supporting `for await` syntax yet (see https://github.com/facebook/hermes/issues/1089)  and with the changes in this PR, `@redux-devtools/remote` can used by React Native developers.

Additional context: Question https://github.com/reduxjs/redux-devtools/discussions/1429 from Discussions section

I had some issues with TypeScript here and there, most of them I actually inherited when forking the project. Would appreciate some help fixing them.

Thank you!

### CODE REVIEW

**Comment by uloco** [comment]
omg can we please merge this! with all the problems flipper and hermes has, this is the only way to use redux devtools on react native right now. Is there any blocker or anything I can do?

**Comment by Methuselah96** [comment]
Sorry for the late response! This should be fixed in `@redux-devtools/remote@0.8.1` ([release](https://github.com/reduxjs/redux-devtools/releases/tag/%40redux-devtools%2Fremote%400.8.1)) by #1496, let me know if not.

**Comment by LunatiqueCoder** [comment]
@Methuselah96 Oh well, would have loved to contribute :) sad to see my PR closed, but happy to see the issue fixed. Will try it out and let you know

**Comment by keeslinp** [comment]
> Sorry for the late response! This should be fixed in `@redux-devtools/remote@0.8.1` ([release](https://github.com/reduxjs/redux-devtools/releases/tag/%40redux-devtools%2Fremote%400.8.1)) by #1496, let me know if not.

@Methuselah96 I'm on `0.8.1` and I'm seeing this error
```Possible Unhandled Promise Rejection (id: 1):
TypeError: Object is not async iterable
TypeError: Object is not async iterable```


I'm thinking it is related to this issue, but I'm not sure.

**Comment by LunatiqueCoder** [comment]
@Methuselah96 Yep, this is not fixed. I will continue using the patch.

image

**Comment by evgenyshenets91** [comment]
same.
image

**Pull request closed without merging**
