### PR TITLE
Support circular references in persistState

### LINKED ISSUE #262: Uncaught TypeError: Converting circular structure to JSON when redux-form
Hi thanks for the awesome project.
Just to report an issue when having redux-devtools and redux-form. 
When you implement the [simplest example in redux-form](https://github.com/erikras/redux-form/blob/master/docs/GettingStarted.md) you get the error `Uncaught TypeError: Converting circular structure to JSON`.

### PR DESCRIPTION
**Pull request by zalmoxisus**
Should fix #262.

### CODE REVIEW

**Comment by stoikerty** [comment]
We're getting a lot of errors when redux dev tools is open.
Any change this can be merged if the fix works?

image

**Comment by zalmoxisus** [comment]
@stoikerty, did you try this patch. Does it solve the issue?

**Comment by stoikerty** [comment]
I would hope it does. I'm willing to try out the patch, not sure how though since it's a chrome extension. How do I do it?

**Comment by stoikerty** [comment]
I forgot to mention, the error started to appear after we started using `redux-form`.

**Comment by zalmoxisus** [comment]
Then it's not related to this PR (unless you added `debug_session` in the url). Could you please open an issue [there](https://github.com/zalmoxisus/redux-devtools-extension) with an example repo or jsfiddle to reproduce? Do you experience this problem also with [our example](http://redux-form.com/5.3.1/#/examples/simple?_k=6s5dgm)?

**Comment by stoikerty** [comment]
Sorry, I thought they were both tightly coupled. I am getting the same error on the example page as well. Should I still create a new issue in the other repo?

gif for [the example](http://redux-form.com/5.3.1/#/examples/simple?_k=6s5dgm) you provided: 
redux-form

**Comment by zalmoxisus** [comment]
@stoikerty, on the settings page (click the last button from the bottom) is the checkbox for serialization checked?

**Comment by stoikerty** [comment]
Yes it is.

image

**Comment by zalmoxisus** [comment]
@stoikerty, checked on Chrome 51, 52 and Canary and cannot reproduce it, also looking in the lifted state don't see any circular reference. Most likely you have another instance (tab with a Redux app) opened, so the error comes not from this example.

Could you please check that and open an issue on [the extension repository](https://github.com/zalmoxisus/redux-devtools-extension), so we can discuss it there?

**Comment by stoikerty** [comment]
@zalmoxisus You're right, it was caused through another tab. Really strange, I thought being in incognito would prevent any overlap. I'm willing to open an issue, but I have a feeling we might have a circular reference that is not related to `redux-form`.

I will investigate, if I can't resolve the issue I'll create an issue in the extension repo with an example/jsfiddle to reproduce it.

**Comment by zalmoxisus** [comment]
@stoikerty, alternatively you can install `jsan` from npm and try to reproduce the problem by executing `jsan.stringify(store.liftedSore.getState())` from your app.

**Comment by stoikerty** [comment]
thanks, I'll check that out

**Comment by zalmoxisus** [comment]
@stoikerty, issues with circular references should be fixed in extension `v2.4.0`. Thanks to @kolodny for working on this. Please confirm.

Of course when adding `debug_session` to the url, `persistState` will still throw till we merge this pr.

**Comment by stoikerty** [comment]
@zalmoxisus I can confirm the error has now disappeared. Thanks for the update, much appreciated.

**Pull request closed without merging**
