### PR TITLE
Convert react-json-tree to TypeScript

### PR DESCRIPTION
**Pull request by Methuselah96**

### CODE REVIEW

**Comment by Methuselah96** [comment]
@timdorr Are you okay with converting some of the code in this repo to TypeScript? I've just been converting it to TypeScript to help me get familiar with the code base and I think it would make it easier to maintain this way.

**Comment by timdorr** [comment]
I don't have a problem with that. Redux is going TS too.

Have you looked into tsdx before? It takes care of all the tooling.

**Comment by Methuselah96** [comment]
No, I haven't. I'll have to look into it at some point.

**Comment by Methuselah96** [comment]
To be re-opened.

**Pull request closed without merging**
